//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/TouchActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @TouchActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @TouchActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""TouchActions"",
    ""maps"": [
        {
            ""name"": ""HorizontalMovement"",
            ""id"": ""acc2675e-c0ff-46e8-9e16-97cee98c6103"",
            ""actions"": [
                {
                    ""name"": ""TouchPosition"",
                    ""type"": ""Value"",
                    ""id"": ""d5fbb52d-b15f-4cd5-9850-c9cdb5006bda"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d263b700-04e2-44f7-933e-07a552a27ef2"",
                    ""path"": ""<Touchscreen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // HorizontalMovement
        m_HorizontalMovement = asset.FindActionMap("HorizontalMovement", throwIfNotFound: true);
        m_HorizontalMovement_TouchPosition = m_HorizontalMovement.FindAction("TouchPosition", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // HorizontalMovement
    private readonly InputActionMap m_HorizontalMovement;
    private List<IHorizontalMovementActions> m_HorizontalMovementActionsCallbackInterfaces = new List<IHorizontalMovementActions>();
    private readonly InputAction m_HorizontalMovement_TouchPosition;
    public struct HorizontalMovementActions
    {
        private @TouchActions m_Wrapper;
        public HorizontalMovementActions(@TouchActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @TouchPosition => m_Wrapper.m_HorizontalMovement_TouchPosition;
        public InputActionMap Get() { return m_Wrapper.m_HorizontalMovement; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(HorizontalMovementActions set) { return set.Get(); }
        public void AddCallbacks(IHorizontalMovementActions instance)
        {
            if (instance == null || m_Wrapper.m_HorizontalMovementActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_HorizontalMovementActionsCallbackInterfaces.Add(instance);
            @TouchPosition.started += instance.OnTouchPosition;
            @TouchPosition.performed += instance.OnTouchPosition;
            @TouchPosition.canceled += instance.OnTouchPosition;
        }

        private void UnregisterCallbacks(IHorizontalMovementActions instance)
        {
            @TouchPosition.started -= instance.OnTouchPosition;
            @TouchPosition.performed -= instance.OnTouchPosition;
            @TouchPosition.canceled -= instance.OnTouchPosition;
        }

        public void RemoveCallbacks(IHorizontalMovementActions instance)
        {
            if (m_Wrapper.m_HorizontalMovementActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IHorizontalMovementActions instance)
        {
            foreach (var item in m_Wrapper.m_HorizontalMovementActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_HorizontalMovementActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public HorizontalMovementActions @HorizontalMovement => new HorizontalMovementActions(this);
    public interface IHorizontalMovementActions
    {
        void OnTouchPosition(InputAction.CallbackContext context);
    }
}
